version: '3.8'

services:
  backend:
    build: ./backend
    depends_on:
      - db
    command: ["./wait-for-it.sh", "db:3306", "--", "flask", "run", "--host=0.0.0.0"]
    container_name: backend
    ports:
      - "5001:5000"
      - "5000:5000"
    environment:
      - SECRET_KEY=super_secret_flask_key
      - FLASK_APP=app:create_app
      - FLASK_ENV=1  
      - MYSQL_HOST=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DB=hotel_db
    volumes:
      - ./static/images:/app/static/image

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules  
    environment:
      - CHOKIDAR_USEPOLLING=true
      - HOST=0.0.0.0

  db:
    image: mysql:5.7
    platform: linux/amd64  # ✅ Fix platform mismatch for M1/M2 Macs
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: hotel_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"  # ✅ Avoid conflict with host machine's MySQL
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
